/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apress_aviplayer_AbstractPlayerActivity */

#ifndef _Included_com_apress_aviplayer_AbstractPlayerActivity
#define _Included_com_apress_aviplayer_AbstractPlayerActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apress_aviplayer_AbstractPlayerActivity
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_apress_aviplayer_AbstractPlayerActivity_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_apress_aviplayer_AbstractPlayerActivity
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_apress_aviplayer_AbstractPlayerActivity_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_apress_aviplayer_AbstractPlayerActivity
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_apress_aviplayer_AbstractPlayerActivity_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_apress_aviplayer_AbstractPlayerActivity
 * Method:    getFrameRate
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_apress_aviplayer_AbstractPlayerActivity_getFrameRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_apress_aviplayer_AbstractPlayerActivity
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_apress_aviplayer_AbstractPlayerActivity_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
